name: SpygChestShop
main: com.spygstudios.chestshop.ChestShop
version: 1.0.0
api-version: 1.16
authors: [ikoli, Ris]
depend: [Vault]

libraries:
  - io.github.ikolihu:spyglib:1.0

commands:
  chestshop:
    aliases: [cs]
