name: SpygChestShop
main: com.spygstudios.chestshop.ChestShop
paper-plugin-loader: com.spygstudios.chestshop.utils.DependencyLoader
version: ${project.version}
api-version: 1.20
authors: [ikoli, Ris]
depend: [Vault]


sona-libraries:
  - com.spygstudios:spyglib:${spyglib.version}
  - org.xerial:sqlite-jdbc:${sqlite.version}
  - com.mysql:mysql-connector-j:${mysql.version}