name: SpygChestShop
main: com.spygstudios.chestshop.ChestShop
version: ${project.version}
api-version: 1.20
authors: [ikoli, Ris]
depend: [Vault]

libraries:
  - com.spygstudios:spyglib:1.0.2

commands:
  chestshop:
    aliases: [cs]
