package com.spygstudios.chestshop.enums;

public enum GuiAction {
    SET_ITEM_AMOUNT, SET_ITEM_PRICE, TOGGLE_NOTIFY, SET_MATERIAL, OPEN_PLAYERS, OPEN_SHOP_INVENTORY, REMOVE_PLAYER, BACK, CLOSE, BUY
}
