package com.spygstudios.chestshop.database;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.concurrent.CompletableFuture;

import com.spygstudios.chestshop.ChestShop;
import com.spygstudios.chestshop.enums.DatabaseType;

public abstract class DatabaseHandler {

    protected final ChestShop plugin;
    protected final DatabaseType databaseType;
    protected Connection connection;

    public DatabaseHandler(ChestShop plugin, DatabaseType databaseType) {
        this.plugin = plugin;
        this.databaseType = databaseType;
        this.connection = null;
    }

    public abstract CompletableFuture<Boolean> initialize();

    public abstract void createTables() throws SQLException;

    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return connection.prepareStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return connection.prepareStatement(sql, autoGeneratedKeys);
    }

    public void close() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
                plugin.getLogger().info("Database connection closed (" + databaseType + ")");
            }
        } catch (SQLException e) {
            plugin.getLogger().severe("Errors occurred while closing the database connection: " + e.getMessage());
        }
    }
}
