package com.spygstudios.chestshop.database;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.logging.Level;

import com.spygstudios.chestshop.ChestShop;
import com.spygstudios.chestshop.enums.DatabaseType;

import lombok.Getter;

public abstract class DatabaseHandler {

    protected ChestShop plugin;
    @Getter
    protected DatabaseType databaseType;
    protected File databaseFile;
    protected Connection connection;
    protected ExecutorService executor;

    public abstract CompletableFuture<Boolean> initialize();

    public abstract void createTables() throws SQLException;

    public CompletableFuture<Void> executeAsync(String sql, Object... params) {
        return CompletableFuture.runAsync(() -> {
            try (PreparedStatement stmt = connection.prepareStatement(sql)) {
                for (int i = 0; i < params.length; i++) {
                    stmt.setObject(i + 1, params[i]);
                }
                stmt.executeUpdate();
            } catch (SQLException e) {
                plugin.getLogger().log(Level.SEVERE, "Hiba az SQL végrehajtása során: " + sql, e);
            }
        }, executor);
    }

    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return connection.prepareStatement(sql);

    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return connection.prepareStatement(sql, autoGeneratedKeys);
    }

    public void close() {
        executor.shutdown();
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
                plugin.getLogger().info("Database connection closed (" + databaseType + ")");
            }
        } catch (SQLException e) {
            plugin.getLogger().severe("Errors occurred while closing the database connection: " + e.getMessage());
        }
    }
}
